### ISSUE TITLE
Emotion Model Implementation Documentation

### ISSUE THREAD

**Issue by JasonJiangs** [caranha/Koudou#57]
This is a roadmap for implementing the emotion model. The tutorial is mainly divided into two parts: implementation and analysis. The details can be extended based on the situation.

### Implementation

The implementation part mainly have three parts, and it is recommended to implement them by order. 

**Part one: the emotion model will be implemented independently.** 

- [x]  IWAN parameter initialization and setting for every agent
- [ ]  Set concern level for each agents
    - [ ]  community factor
    - [ ]  family infection
    - [ ]  self-infection
    - [ ]  crowding factor
    - [ ]  constant decay
- [x]  Connect concern level with agents’ emotion changes

**Part two: connect the emotion states with mask-wearing behaviors**

Emotion changes will change two parameters of the agents: mask forget rate and intention of changing mask behavior. The logic is that for every agent, they will set a mask forget rate and intention at the beginning of everyday based on the emotion states, then the parameters will be used for the rest of the day and reset for the next day.

- [ ]  mask forget rate
- [ ]  intention of mask changing

**Part three: connect the emotion states with evacuation events**

The crowdedness of the evacuation center will influence the concern level, referring to the crowding factor in the part one.

### Analysis

Those are the recommended analysis that can be conducted for evaluation.

- [ ]  the average of the concern level over time: since the concern levels are limited between 0.5 and 1.5, it can be used to monitor if the concern level is balanced.
- [ ]  emotion proportion of the population over time
- [ ]  analyze the emotional change at significant time steps like the start and end of the evacuation
- [ ]  analyze the contribution of the crowdedness to the concern level during the evacuation
- [ ]  analyze mask wearing proportion over time, since we have connected it with the emotion model
- [ ]  draw heat maps to reflect the emotion distribution geographically of different stages: before evac, evac, and after evac, etc.

**Comment by JasonJiangs** [comment]
The document reflects the basic implementation order and content for the emotion model. For details, please refer to the emotion model part in Wiki.
